server:
  port: ${SERVER_PORT:9081}
  undertow:
    buffer-size: 1024
    direct-buffers: true

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:actuator}

management:

  # change actuator port
  #server:
  #  port: 8081

  endpoints:
    web:
      exposure:
#        include: ${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE:prometheus}
        include: ${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE:*}

      # change actuator path
      #base-path: /
      # overwrite actuator path http://localhost:8081/healthcheck
      #path-mapping:
      #  health: healthcheck

  endpoint:
    health:
      show-details: ${MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS:ALWAYS}

      #test health group
      #http://localhost:9081/actuator/health/custom
      group:
        custom:
          include: my

      # k8s
      probes:
        enabled: true

  # enable env info builder
  # info list : build(META-INF/build-info.properties resource.) env git(git.properties resource.) java os
  info:
    env:
      enabled: true
    os:
      enabled: true
    java:
      enabled: true


test:
  meters:
    - className: simulateBusinessService
      funcName: getCountFromRedis
      tags: sys,core1
    - className: simulateBusinessService
      funcName: getCountFromRedis
      tags: sys,core2

